### ISSUE TITLE
Focusing the CMS-SIG to have actionable Goals

### ISSUE THREAD

**Issue by mfacenet** [drud/sig-cms#6]
To enable this SIG to have actionable goals I'm making a multi-faceted proposal to handle the organization and mission of the SIG.  This proposal is broken down into several sections which are somewhat severable from others; This is not an all or nothing proposal.
Proposal for the management of the group and it's mission:
* Define a "Mission Statement", a short statement outlining the purpose of the group so that new members and non-members viewing this group for this first time have an understanding of what we are aiming to accomplish.  Example, "To work with open source CMS projects to enable their users to rapidly and easily deploy their projects on Kubernetes"
* Create a framework for documenting our involvement with Open Source Projects, as members leave and new members join OSS projects it's important that an easily readable log of conversations, decisions, and work exists.
* Create a framework for new project adoption, as there are many OSS CMS projects out there, focusing on the largest will get a large ROI, however, to ignore or not provide resources to smaller projects would be limiting in the long term.  As such, general guidelines and recommendations are highly beneficial, the content here would be tailored depending on the areas we accept as part of our SIG.
Proposal for Contributions to OSS projects:
* Work with the projects to create Dockerfiles that the project would later own and, optionally, maintain.
* Create reference deployments of OSS Projects to contribute back to the project, where plausible, this should be coupled with documentation on how to deploy the project (e.g. Drupal, Joomla, Ghost, etc) on Kubernetes and how to build custom containers using Official or Community contributed docker containers, buildpacks, etc.
* Contribute Documentation to the project about running in containers and kubernetes, this would include a list of common helpful plugins that end-users can use to resolve container specific projects.
* Package Management, where plausible, contribute the reference architecture in raw yaml, helm, or other package management format.
Areas where we're suited to be advocates on behalf of users:
* Identitfy and address tickets that resolve issues specific to containers and/or kubernetes that may not be otherwise prioritized, where possible it would be beneficial to open Pull Requests resolving issues and working directly with the OSS Projects developers to ensure that the solution integrates into the project.
* Identify a "certification" process that certifies that a specific project (e.g. Drupal) deployed on a containerized platform isn't missing critical functionality or otherwise hampered in it's functional state.
Finally, this is a discussion and not a blue print, none of the ideas set forth above are meant to be comprehensive or may even go above what we should be doing as a SIG, please feel free to critically discuss any aspect of this ticket, the final intention is to give this group a specific outlined purpose that we, as its members, can work towards accomplishing.

**Comment by cyberswat** [comment]
If you'd like to see a walktrhoguh of this proposal the video is available at https://youtu.be/ijljdu70gs4

**Comment by rfay** [comment]
Wow Shawn! I should probably delete this repo right? Any reason to keep it around?
